# Generated by Django 3.0.8 on 2020-07-23 04:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='job',
            old_name='link_webste',
            new_name='link_website',
        ),
    ]
